init -1:
    
    define Rogue_thresholds = {
        "talk_late": [0, 50],

        "temporary_follow": [0, 50],
        "follow": [0, 75],

        "friendship": [25, 50],
        "dating": [100, 100],
        "relationship": [250, 175],
        "love": [950, 950],

        "sleepover": [0, 0],

        "shirk_responsibilities": [0, 300],

        "customize_pubes": [425, 425],

        "polyamory": [900, 900],

        "see_bra": [0, 150],
        "give_bra": [425, 425],
        "see_underwear": [0, 175],
        "give_underwear": [525, 525],
        "see_breasts": [200, 200],
        "see_breasts_without_asking": [950, 950],
        "see_pussy": [375, 375],
        "see_pussy_without_asking": [950, 950],

        "change_Outfit": [100, 175],
        "change_in_public": [275, 275],

        "hookup": [130, 130],

        "massage": [125, 150],
        "kiss": [50, 50],
        "makeout": [130, 130],
        "spank": [825, 950],
        "choke": [825, 950],

        "touch_thighs_over_clothes": [150, 150],
        "touch_thighs_higher_over_clothes": [175, 175],
        "touch_thighs": [160, 160],
        "touch_thighs_higher": [185, 185],
        "touch_breasts_over_clothes": [175, 175],
        "touch_breasts": [210, 210],
        "pinch_nipples": [225, 225],
        "suck_nipples": [250, 250],
        "touch_pussy_over_clothes": [250, 250],
        "touch_pussy": [325, 325],
        "finger_pussy": [600, 550],
        "eat_pussy": [575, 575],
        "grab_ass_over_clothes": [150, 150],
        "grab_ass": [210, 210],
        "finger_ass": [615, 615],
        "eat_ass": [650, 650],

        "handjob": [225, 225],
        "fondle_balls": [375, 375],
        "blowjob": [350, 350],
        "suck_balls": [400, 400],
        "deepthroat": [650, 600],
        "titjob": [550, 550],
        "footjob": [760, 760],

        "striptease": [400, 400],
        "self_touch_pussy": [525, 525],
        "self_finger_ass": [525, 525],
        "self_vibrator": [700, 700],
        "self_dildo_pussy": [950, 950],
        "self_dildo_ass": [950, 950],
        "jerk_off": [525, 525],
        
        "grind_pussy": [800, 775],
        "grind_ass": [750, 750],
        "sex": [950, 950],
        "anal": [875, 875],
        "vibrator": [700, 700],
        "dildo_pussy": [950, 950],
        "dildo_ass": [950, 950],
        "ass_to_mouth": [925, 925],
        "double_penetrate": [950, 950],
        
        "cumshot_belly": [400, 400],
        "cumshot_breasts": [410, 410],
        "cumshot_face": [420, 420],
        "cumshot_hair": [450, 450],
        "cumshot_back": [460, 460],
        "cumshot_ass": [470, 470],
        "cumshot_feet": [480, 480],

        "creampie": [950, 950],
        "anal_creampie": [900, 900],
        "cum_in_mouth": [600, 600],
        "cum_down_throat": [800, 800],

        "clean_cum": [0, 0],
        "swallow_cum": [675, 675],
        "wear_cum": [850, 850],

        "standing": [0, 0],
        "masturbation": [0, 0],
        "kneeling": [0, 0],
        "hands_and_knees": [0, 0],
        "missionary": [0, 0],
        "cowgirl": [0, 0],
        "doggy": [0, 0],
        "footjob": [0, 0],
        
        "lesbian": [850, 850],
        
        "exhibitionism": [1001, 1001],
        "rough_play": [825, 950],
        
        "send_underwear_pics": [225, 250],
        "send_nudes": [425, 450],
        
        "flirting_aa": [0, 0],
        "flirting_ab": [0, 0],
        "flirting_ac": [0, 0],
        "flirting_ad": [0, 0],
        "flirting_ae": [0, 0],
        "flirting_af": [0, 0],
        "flirting_ag": [0, 0],
        "flirting_ah": [0, 0],
        "flirting_ai": [0, 0],
        "flirting_aj": [0, 0],
        "flirting_ak": [0, 0],
        "flirting_al": [0, 0],
        "flirting_am": [0, 0],
        "flirting_an": [0, 0],
        "flirting_ao": [0, 0],
        "flirting_ap": [0, 0],
        "flirting_aq": [0, 0],
        "flirting_ar": [0, 0],
        "flirting_b": [0, 0],
        "flirting_c": [0, 0],
        "flirting_d": [50, 50],
        "flirting_ea": [50, 50],
        "flirting_eb": [50, 50],
        "flirting_f": [0, 0],
        "flirting_g": [125, 125],
        "flirting_h": [125, 125],
        "flirting_i": [125, 125],
        "flirting_ja": [0, 150],
        "flirting_jb": [0, 175],
        "flirting_jc": [200, 200],
        "flirting_jd": [375, 375],
        "flirting_ka": [425, 425],
        "flirting_kb": [525, 525],
        "flirting_l": [0, 0],
        "flirting_ma": [210, 210],
        "flirting_mb": [300, 300],
        "flirting_mc": [325, 325],
        "flirting_na": [0, 0],
        "flirting_nb": [0, 0],
        "flirting_nc": [0, 0],
        "flirting_oa": [200, 200],
        "flirting_ob": [200, 200],
        "flirting_pa": [0, 0],
        "flirting_pb": [0, 0],
        "flirting_pc": [0, 0],
        "flirting_pd": [0, 0],
        "flirting_qa": [0, 0],
        "flirting_qb": [0, 0],
        "flirting_qc": [0, 0],
        "flirting_r": [0, 0]}

    define Rogue_conditions = {
        "love": ["EventScheduler.Events['Rogue_I_love_you'].completed"],

        "sleepover": ["Rogue in Partners"],

        "see_bra": ["Rogue in Partners"],
        "give_bra": ["Rogue in Partners"],
        "see_underwear": ["Rogue in Partners"],
        "give_underwear": ["Rogue in Partners"],
        "see_breasts": ["Rogue in Partners"],
        "see_breasts_without_asking": ["Rogue in Partners"],
        "see_pussy": ["Rogue in Partners"],
        "see_pussy_without_asking": ["Rogue in Partners"],

        "change_Outfit": ["Rogue in Partners"],
        "change_in_public": ["Rogue in Partners"],

        "hookup": ["Rogue in Partners"],

        "spank": ["Rogue in Partners"],
        "choke": ["Rogue in Partners"],

        "touch_thighs": ["Rogue in Partners"],
        "touch_thighs_higher": ["Rogue in Partners"],
        "touch_breasts_over_clothes": ["Rogue in Partners"],
        "touch_breasts": ["Rogue in Partners"],
        "pinch_nipples": ["Rogue in Partners"],
        "suck_nipples": ["Rogue in Partners"],
        "touch_pussy_over_clothes": ["Rogue in Partners"],
        "touch_pussy": ["Rogue in Partners"],
        "finger_pussy": ["Rogue in Partners"],
        "eat_pussy": ["Rogue in Partners"],
        "grab_ass_over_clothes": ["Rogue in Partners"],
        "grab_ass": ["Rogue in Partners"],
        "finger_ass": ["Rogue in Partners"],
        "eat_ass": ["Rogue in Partners"],

        "handjob": ["Rogue in Partners"],
        "fondle_balls": ["Rogue in Partners"],
        "blowjob": ["Rogue in Partners"],
        "suck_balls": ["Rogue in Partners"],
        "deepthroat": ["Rogue in Partners"],
        "titjob": ["Rogue in Partners"],
        "footjob": ["Rogue in Partners"],

        "striptease": ["Rogue in Partners"],
        "self_touch_pussy": ["Rogue in Partners"],
        "self_finger_ass": ["Rogue in Partners"],
        "self_vibrator": ["Rogue in Partners"],
        "self_dildo_pussy": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "self_dildo_ass": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "jerk_off": ["Rogue in Partners"],
        
        "grind_pussy": ["Rogue in Partners"],
        "grind_ass": ["Rogue in Partners"],
        "sex": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "anal": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "vibrator": ["Rogue in Partners"],
        "dildo_pussy": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "dildo_ass": ["Rogue in Partners", "EventScheduler.Events['Rogue_first_sex'].completed"],
        "ass_to_mouth": ["Rogue in Partners"],
        "double_penetrate": ["Rogue in Partners"],
        
        "cumshot_belly": ["Rogue in Partners"],
        "cumshot_breasts": ["Rogue in Partners"],
        "cumshot_face": ["Rogue in Partners"],
        "cumshot_hair": ["Rogue in Partners"],
        "cumshot_back": ["Rogue in Partners"],
        "cumshot_ass": ["Rogue in Partners"],
        "cumshot_feet": ["Rogue in Partners"],

        "creampie": ["Rogue in Partners"],
        "anal_creampie": ["Rogue in Partners"],
        "cum_in_mouth": ["Rogue in Partners"],
        "cum_down_throat": ["Rogue in Partners"],

        "clean_cum": ["Rogue in Partners"],
        "swallow_cum": ["Rogue in Partners"],
        "wear_cum": ["Rogue in Partners"],

        "kneeling": ["Rogue in Partners"],
        "hands_and_knees": ["Rogue in Partners"],
        "missionary": ["Rogue in Partners"],
        "cowgirl": ["Rogue in Partners"],
        "doggy": ["Rogue in Partners"],
        "footjob": ["Rogue in Partners"],
        
        "lesbian": ["Rogue in Partners"],
        
        "exhibitionism": ["Rogue in Partners"],
        "rough_play": ["Rogue in Partners"],
        
        "send_underwear_pics": ["Rogue in Partners"],
        "send_nudes": ["Rogue in Partners"],
        
        "flirting_ea": ["Rogue.History.check('kiss')"],
        "flirting_eb": ["Rogue.History.check('kiss')"],
        "flirting_h": ["Rogue in Partners"],
        "flirting_i": ["Rogue in Partners"],
        "flirting_ja": ["Rogue in Partners"],
        "flirting_jb": ["Rogue in Partners"],
        "flirting_jc": ["Rogue in Partners"],
        "flirting_jd": ["Rogue in Partners"],
        "flirting_ka": ["Rogue in Partners"],
        "flirting_kb": ["Rogue in Partners"],
        "flirting_l": ["Rogue.check_traits('quirk')"],
        "flirting_na": ["Rogue.check_traits('quirk')"],
        "flirting_nb": ["Rogue.check_traits('quirk')"],
        "flirting_nc": ["Rogue.check_traits('quirk')"],
        "flirting_ma": ["Rogue in Partners"],
        "flirting_mb": ["Rogue in Partners"],
        "flirting_mc": ["Rogue in Partners"],
        "flirting_oa": ["Rogue.History.check('kiss')"],
        "flirting_ob": ["Rogue.History.check('kiss')"],
        "flirting_pa": ["Rogue.check_traits('quirk')"],
        "flirting_pb": ["Rogue.check_traits('quirk')"],
        "flirting_pc": ["Rogue.check_traits('quirk')"],
        "flirting_pd": ["Rogue.check_traits('quirk')"],
        "flirting_qa": ["Rogue.check_traits('quirk')"],
        "flirting_qb": ["Rogue.check_traits('quirk')"],
        "flirting_qc": ["Rogue.check_traits('quirk')"],
        "flirting_r": ["Rogue in Partners", "EventScheduler.Events['Rogue_I_love_you'].completed"],
        
        "sexy_gifts": ["Rogue in Partners"],
        
        "piercing": ["Rogue in Partners"],
        
        "sex_toy": ["Rogue in Partners"],
        
        "new_Outfit": ["Rogue in Partners"]}