init -1:

    define Rogue_gift_thresholds = {
        "box_of_chocolates": [0, 0],
        "candle": [0, 0],
        "combat_manual": [0, 0],
        "designer_purse": [0, 0],
        "flowers": [0, 0],
        "flowery_perfume": [0, 0],
        "fruity_perfume": [0, 0],
        "horror_novel": [0, 0],
        "journal": [0, 0],
        "mystery_novel": [0, 0],
        "plant1": [0, 0],
        "plant2": [0, 0],
        "plant3": [0, 0],
        "spicy_perfume": [0, 0],
        "steamy_romance_novel": [0, 0],
        "tea": [0, 0],
        "teddy_bear": [0, 0],
        "watercolors": [0, 0],
        "wholesome_romance_novel": [0, 0],

        "dildo": [0, 0],
        "heart_anal_plug": [0, 0],
        "remote_vibrator": [0, 0],
        "round_anal_plug": [0, 0],
        "vibrator": [0, 0],

        "belly_piercing": [0, 0],
        "barbell_nipple_piercings": [0, 0],
        "ring_nipple_piercings": [0, 0],
        "barbell_labia_piercings": [0, 0],
        "ring_labia_piercings": [0, 0],
        
        "acoustic_guitar": [0, 0],
        "band_posters": [0, 0],
        "baseball_flag": [0, 0],
        "boxing_kit": [0, 0],
        "camera": [0, 0],
        "mirror": [0, 0],
        "MMA_gloves": [0, 0],
        "motorcycle_helmet": [0, 0],
        "motorcycle_posters": [0, 0],
        "occult_posters": [0, 0],
        "record_player": [0, 0]}

    define Rogue_gift_bonuses = {
        "box_of_chocolates": [0, 0],
        "candle": [0, 0],
        "combat_manual": [0, 0],
        "designer_purse": [0, 0],
        "flowers": [0, 0],
        "flowery_perfume": [0, 0],
        "fruity_perfume": [0, 0],
        "horror_novel": [0, 0],
        "journal": [0, 0],
        "mystery_novel": [0, 0],
        "plant1": [0, 0],
        "plant2": [0, 0],
        "plant3": [0, 0],
        "spicy_perfume": [0, 0],
        "steamy_romance_novel": [0, 0],
        "tea": [0, 0],
        "teddy_bear": [0, 0],
        "watercolors": [0, 0],
        "wholesome_romance_novel": [0, 0],

        "dildo": [0, 0],
        "heart_anal_plug": [0, 0],
        "remote_vibrator": [0, 0],
        "round_anal_plug": [0, 0],
        "vibrator": [0, 0],

        "belly_piercing": [0, 0],
        "barbell_nipple_piercings": [0, 0],
        "ring_nipple_piercings": [0, 0],
        "barbell_labia_piercings": [0, 0],
        "ring_labia_piercings": [0, 0],
        
        "acoustic_guitar": [0, 0],
        "band_posters": [0, 0],
        "baseball_flag": [0, 0],
        "boxing_kit": [0, 0],
        "camera": [0, 0],
        "mirror": [0, 0],
        "MMA_gloves": [0, 0],
        "motorcycle_helmet": [0, 0],
        "motorcycle_posters": [0, 0],
        "occult_posters": [0, 0],
        "record_player": [0, 0]}