init -1:

    define Rogue_gift_thresholds = {
        "box_of_chocolates": [25, 25],
        "candle": [75, 75],
        "combat_manual": [25, 25],
        "designer_purse": [0, 0],
        "flowers": [100, 100],
        "flowery_perfume": [300, 300],
        "fruity_perfume": [300, 300],
        "horror_novel": [25, 25],
        "journal": [50, 50],
        "mystery_novel": [25, 25],
        "plant1": [100, 100],
        "plant2": [150, 150],
        "plant3": [200, 200],
        "spicy_perfume": [300, 300],
        "steamy_romance_novel": [150, 150],
        "tea": [50, 50],
        "teddy_bear": [100, 100],
        "watercolors": [85, 85],
        "wholesome_romance_novel": [150, 150],

        "dildo": [750, 750],
        "heart_anal_plug": [800, 800],
        "remote_vibrator": [900, 900],
        "round_anal_plug": [800, 800],
        "vibrator": [600, 600],

        "belly_piercing": [500, 500],
        "barbell_nipple_piercings": [750, 750],
        "ring_nipple_piercings": [750, 750],
        "barbell_labia_piercings": [950, 950],
        "ring_labia_piercings": [950, 950],
        
        "acoustic_guitar": [0, 0],
        "band_posters": [0, 0],
        "baseball_flag": [0, 0],
        "boxing_kit": [0, 0],
        "camera": [0, 0],
        "mirror": [0, 0],
        "MMA_gloves": [0, 0],
        "motorcycle_helmet": [0, 0],
        "motorcycle_posters": [0, 0],
        "occult_posters": [0, 0],
        "record_player": [0, 0]}

    define Rogue_gift_bonuses = {
        "box_of_chocolates": [medium_stat, 0],
        "candle": [medium_stat, medium_stat],
        "combat_manual": [small_stat, medium_stat],
        "designer_purse": [0, 0],
        "flowers": [0, 0],
        "flowery_perfume": [0, 0],
        "fruity_perfume": [0, 0],
        "horror_novel": [medium_stat, medium_stat],
        "journal": [0, 0],
        "mystery_novel": [medium_stat, medium_stat],
        "plant1": [small_stat, small_stat],
        "plant2": [medium_stat, medium_stat],
        "plant3": [large_stat, large_stat],
        "spicy_perfume": [0, 0],
        "steamy_romance_novel": [large_stat, small_stat],
        "tea": [0, 0],
        "teddy_bear": [large_stat, small_stat],
        "watercolors": [0, 0],
        "wholesome_romance_novel": [large_stat, small_stat],

        "dildo": [0, 0],
        "heart_anal_plug": [0, 0],
        "remote_vibrator": [0, 0],
        "round_anal_plug": [0, 0],
        "vibrator": [0, 0],

        "belly_piercing": [0, 0],
        "barbell_nipple_piercings": [0, 0],
        "ring_nipple_piercings": [0, 0],
        "barbell_labia_piercings": [0, 0],
        "ring_labia_piercings": [0, 0],
        
        "acoustic_guitar": [massive_stat, massive_stat],
        "band_posters": [0, 0],
        "baseball_flag": [medium_stat, medium_stat],
        "boxing_kit": [0, 0],
        "camera": [massive_stat, massive_stat],
        "mirror": [large_stat, medium_stat],
        "MMA_gloves": [0, 0],
        "motorcycle_helmet": [0, 0],
        "motorcycle_posters": [0, 0],
        "occult_posters": [medium_stat, medium_stat],
        "record_player": [0, 0]}