init -1:
    
    define Laura_thresholds = {
        "talk_late": [0, 100],

        "temporary_follow": [0, 100],
        "follow": [0, 115],

        "friendship": [50, 75],
        "dating": [75, 100],
        "relationship": [100, 150],
        "love": [775, 850],

        "sleepover": [0, 0],

        "shirk_responsibilities": [0, 100],

        "customize_pubes": [325, 375],

        "polyamory": [875, 950],

        "see_bra": [0, 75],
        "give_bra": [325, 350],
        "see_underwear": [0, 75],
        "give_underwear": [350, 475],
        "see_breasts": [125, 150],
        "see_breasts_without_asking": [1001, 1001],
        "see_pussy": [125, 175],
        "see_pussy_without_asking": [1001, 1001],

        "change_Outfit": [100, 200],
        "change_in_public": [275, 300],

        "hookup": [150, 200],

        "massage": [125, 225],
        "kiss": [75, 100],
        "makeout": [150, 200],
        "spank": [750, 775],
        "choke": [750, 775],

        "touch_thighs_over_clothes": [125, 150],
        "touch_thighs_higher_over_clothes": [125, 175],
        "touch_thighs": [125, 175],
        "touch_thighs_higher": [150, 200],
        "touch_breasts_over_clothes": [125, 175],
        "touch_breasts": [175, 225],
        "pinch_nipples": [200, 225],
        "suck_nipples": [250, 250],
        "touch_pussy_over_clothes": [150, 175],
        "touch_pussy": [500, 575],
        "finger_pussy": [550, 600],
        "eat_pussy": [575, 625],
        "grab_ass_over_clothes": [125, 150],
        "grab_ass": [150, 175],
        "finger_ass": [575, 625],
        "eat_ass": [625, 675],

        "handjob": [150, 225],
        "fondle_balls": [350, 400],
        "blowjob": [575, 625],
        "suck_balls": [600, 675],
        "deepthroat": [625, 725],
        "titjob": [750, 800],
        "footjob": [700, 775],

        "striptease": [175, 225],
        "self_touch_pussy": [250, 325],
        "self_finger_ass": [250, 325],
        "self_vibrator": [550, 625],
        "self_dildo_pussy": [750, 850],
        "self_dildo_ass": [875, 925],
        "jerk_off": [500, 575],
        
        "grind_pussy": [750, 825],
        "grind_ass": [825, 900],
        "sex": [850, 900],
        "anal": [875, 925],
        "vibrator": [550, 625],
        "dildo_pussy": [750, 850],
        "dildo_ass": [875, 925],
        "ass_to_mouth": [925, 950],
        "double_penetrate": [950, 950],
        
        "cumshot_belly": [400, 420],
        "cumshot_breasts": [420, 430],
        "cumshot_face": [400, 420],
        "cumshot_hair": [460, 470],
        "cumshot_back": [470, 525],
        "cumshot_ass": [490, 525],
        "cumshot_feet": [480, 490],

        "creampie": [925, 950],
        "anal_creampie": [925, 975],
        "cum_in_mouth": [600, 625],
        "cum_down_throat": [825, 850],

        "clean_cum": [0, 0],
        "swallow_cum": [650, 675],
        "wear_cum": [800, 825],

        "standing": [0, 0],
        "masturbation": [0, 0],
        "kneeling": [0, 0],
        "hands_and_knees": [0, 0],
        "missionary": [0, 0],
        "cowgirl": [0, 0],
        "doggy": [0, 0],
        "footjob": [0, 0],
        
        "lesbian": [900, 925],
        
        "exhibitionism": [1001, 1001],
        "rough_play": [750, 775],
        
        "send_underwear_pics": [150, 175],
        "send_nudes": [475, 400],
        
        "flirting_aa": [0, 0],
        "flirting_ab": [0, 0],
        "flirting_ac": [0, 0],
        "flirting_ad": [100, 150],
        "flirting_ae": [100, 150],
        "flirting_af": [0, 0],
        "flirting_ag": [75, 100],
        "flirting_ah": [0, 0],
        "flirting_ai": [775, 850],
        "flirting_aj": [0, 0],
        "flirting_ak": [50, 75],
        "flirting_al": [0, 0],
        "flirting_am": [0, 0],
        "flirting_an": [0, 0],
        "flirting_ao": [0, 0],
        "flirting_ap": [0, 0],
        "flirting_aq": [0, 0],
        "flirting_ar": [0, 0],
        "flirting_b": [0, 0],
        "flirting_c": [0, 0],
        "flirting_d": [75, 100],
        "flirting_ea": [75, 100],
        "flirting_eb": [75, 100],
        "flirting_f": [0, 0],
        "flirting_g": [100, 150],
        "flirting_h": [100, 150],
        "flirting_i": [100, 150],
        "flirting_ja": [0, 150],
        "flirting_jb": [0, 150],
        "flirting_jc": [125, 150],
        "flirting_jd": [125, 175],
        "flirting_ka": [325, 350],
        "flirting_kb": [350, 475],
        "flirting_l": [175, 200],
        "flirting_ma": [175, 225],
        "flirting_mb": [150, 175],
        "flirting_mc": [500, 575],
        "flirting_na": [0, 0],
        "flirting_nb": [0, 0],
        "flirting_nc": [0, 0],
        "flirting_oa": [125, 150],
        "flirting_ob": [125, 150],
        "flirting_pa": [0, 0],
        "flirting_pb": [0, 0],
        "flirting_pc": [0, 0],
        "flirting_pd": [0, 0],
        "flirting_qa": [0, 0],
        "flirting_qb": [0, 0],
        "flirting_qc": [0, 0],
        "flirting_r": [0, 0]}

    define Laura_conditions = {
        "love": ["EventScheduler.Events['Laura_I_love_you'].completed"],

        "sleepover": ["Laura in Partners"],

        "see_bra": ["Laura in Partners"],
        "give_bra": ["Laura in Partners"],
        "see_underwear": ["Laura in Partners"],
        "give_underwear": ["Laura in Partners"],
        "see_breasts": ["Laura in Partners"],
        "see_breasts_without_asking": ["Laura in Partners"],
        "see_pussy": ["Laura in Partners"],
        "see_pussy_without_asking": ["Laura in Partners"],

        "change_Outfit": ["Laura in Partners"],
        "change_in_public": ["Laura in Partners"],

        "hookup": ["Laura in Partners"],

        "spank": ["Laura in Partners"],
        "choke": ["Laura in Partners"],

        "touch_thighs": ["Laura in Partners"],
        "touch_thighs_higher": ["Laura in Partners"],
        "touch_breasts_over_clothes": ["Laura in Partners"],
        "touch_breasts": ["Laura in Partners"],
        "pinch_nipples": ["Laura in Partners"],
        "suck_nipples": ["Laura in Partners"],
        "touch_pussy_over_clothes": ["Laura in Partners"],
        "touch_pussy": ["Laura in Partners"],
        "finger_pussy": ["Laura in Partners"],
        "eat_pussy": ["Laura in Partners"],
        "grab_ass_over_clothes": ["Laura in Partners"],
        "grab_ass": ["Laura in Partners"],
        "finger_ass": ["Laura in Partners"],
        "eat_ass": ["Laura in Partners"],

        "handjob": ["Laura in Partners"],
        "fondle_balls": ["Laura in Partners"],
        "blowjob": ["Laura in Partners"],
        "suck_balls": ["Laura in Partners"],
        "deepthroat": ["Laura in Partners"],
        "titjob": ["Laura in Partners"],
        "footjob": ["Laura in Partners"],

        "striptease": ["Laura in Partners"],
        "self_touch_pussy": ["Laura in Partners"],
        "self_finger_ass": ["Laura in Partners"],
        "self_vibrator": ["Laura in Partners"],
        "self_dildo_pussy": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_two'].completed"],
        "self_dildo_ass": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_two'].completed"],
        "jerk_off": ["Laura in Partners"],
        
        "grind_pussy": ["Laura in Partners"],
        "grind_ass": ["Laura in Partners"],
        "sex": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_one'].completed"],
        "anal": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_two'].completed"],
        "vibrator": ["Laura in Partners"],
        "dildo_pussy": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_two'].completed"],
        "dildo_ass": ["Laura in Partners", "EventScheduler.Events['Laura_first_sex_part_two'].completed"],
        "ass_to_mouth": ["Laura in Partners"],
        "double_penetrate": ["Laura in Partners"],
        
        "cumshot_belly": ["Laura in Partners"],
        "cumshot_breasts": ["Laura in Partners"],
        "cumshot_face": ["Laura in Partners"],
        "cumshot_hair": ["Laura in Partners"],
        "cumshot_back": ["Laura in Partners"],
        "cumshot_ass": ["Laura in Partners"],
        "cumshot_feet": ["Laura in Partners"],

        "creampie": ["Laura in Partners"],
        "anal_creampie": ["Laura in Partners"],
        "cum_in_mouth": ["Laura in Partners"],
        "cum_down_throat": ["Laura in Partners"],

        "clean_cum": ["Laura in Partners"],
        "swallow_cum": ["Laura in Partners"],
        "wear_cum": ["Laura in Partners"],

        "kneeling": ["Laura in Partners"],
        "hands_and_knees": ["Laura in Partners"],
        "missionary": ["Laura in Partners"],
        "cowgirl": ["Laura in Partners"],
        "doggy": ["Laura in Partners"],
        "footjob": ["Laura in Partners"],
        
        "lesbian": ["Laura in Partners"],
        
        "exhibitionism": ["Laura in Partners"],
        "rough_play": ["Laura in Partners"],
        
        "send_underwear_pics": ["Laura in Partners"],
        "send_nudes": ["Laura in Partners"],
        
        "flirting_ea": ["Laura.History.check('kiss')"],
        "flirting_eb": ["Laura.History.check('kiss')"],
        "flirting_h": ["Laura in Partners"],
        "flirting_i": ["Laura in Partners"],
        "flirting_ja": ["Laura in Partners"],
        "flirting_jb": ["Laura in Partners"],
        "flirting_jc": ["Laura in Partners"],
        "flirting_jd": ["Laura in Partners"],
        "flirting_ka": ["Laura in Partners"],
        "flirting_kb": ["Laura in Partners"],
        "flirting_l": ["Laura.check_traits('quirk')"],
        "flirting_na": ["Laura.check_traits('quirk')"],
        "flirting_nb": ["Laura.check_traits('quirk')"],
        "flirting_nc": ["Laura.check_traits('quirk')"],
        "flirting_ma": ["Laura in Partners"],
        "flirting_mb": ["Laura in Partners"],
        "flirting_mc": ["Laura in Partners"],
        "flirting_oa": ["Laura.History.check('kiss')"],
        "flirting_ob": ["Laura.History.check('kiss')"],
        "flirting_pa": ["Laura.check_traits('quirk')"],
        "flirting_pb": ["Laura.check_traits('quirk')"],
        "flirting_pc": ["Laura.check_traits('quirk')"],
        "flirting_pd": ["Laura.check_traits('quirk')"],
        "flirting_qa": ["Laura.check_traits('quirk')"],
        "flirting_qb": ["Laura.check_traits('quirk')"],
        "flirting_qc": ["Laura.check_traits('quirk')"],
        "flirting_r": ["Laura in Partners", "EventScheduler.Events['Laura_I_love_you'].completed"],
        
        "sexy_gifts": ["Laura in Partners"],
        
        "piercing": ["Laura in Partners"],
        
        "sex_toy": ["Laura in Partners"],
        
        "new_Outfit": ["Laura in Partners"]}