label update_Laura_database:
    $ Laura.database["stats"] = [
        "Name: Laura Kinney\nCodename: X-23\nAge: 18\nDoB: August 2nd\nHeight: 5'1\"\nHair: Black\nEyes: Green\nPowers: Enhanced Strength, Durability, Senses, Reflexes, Agility; Adamantium-Plated 'Claws' in Hands and Feet; Healing Factor"]

    $ Laura.database["description"] = [
        "X-23 is something of a special case here at the school. The first we were made aware of her existence was when Logan showed up at the school with her, asking we take her in. According to his information, she was a genetically-engineered clone of himself, created from samples taken from him during his time with the Weapon X project. Until her rescue, the girl, who we believe to be called 'Laura', was kept in conditions that could charitably be considered 'inhumane.' From birth, she was raised to be an assassin for hire and was, in essence, kept caged between missions, barely receiving any human contact or socialization - to quote Logan: \"she knows a hundred ways to kill you with her bare hands, but doesn't know how to say 'thanks' when you hand her something.\". Unsurprisingly, X-23 has found it difficult to mix with other students, leading to some unfortunate clashes with people unaware of her unique status. Even worse, the few times these clashes have become physical, the other party has come away worse off. While no one has been seriously injured as yet, it is a worry that that may not always be the case.\n\nAs mentioned, X-23 was cloned from samples taken from Logan (note: try and find out what means for her relationship to Logan: daughter? Sister?), meaning she shares the majority of his abilities. X-23 boasts enhanced strength and reflexes, and while she lacks his brute strength, she is more agile and capable of out-maneuvering him. This may be, at least in part, due to the fact that she lacks the fully-plated adamantium skeleton he has, having adamantium plated only on her claws. She also has a different configuration of claws, having only two on each hand, compared to his three. She does, however, have a third claw emerging from between her toes. She also boasts the same enhanced senses, primarily hearing, smell and sight Logan has. In addition, due to her training since birth, X-23 has almost peerless fighting ability, being able to use a multitude of combat styles and techniques, as well as excelling with just about any weapon we have put in her hands.\n\nOnce again, due to her upbringing, or lack thereof, X-23 has become isolated from the rest of her peers. While this has had no significant effect on her mental state - indeed, I would be inclined to believe it to be her natural state of being - this has had a detrimental effect on our attempts to introduce her to the other students. She has shown no interest in classes, despite showing signs that she could easily pass each one with flying colors. If X-23 is not training, she is asleep. For her, there is literally nothing else. And while she has shown a willingness to take orders in training exercises, she will frequently run ahead of everyone and complete objectives by herself, only saying that 'it is easier' for her to do things solo. For now, we are allowing her to work more independently, but are looking at ways of trying to integrate her into the student body at large."]

    $ Laura.database["study_materials"] = [
        "RECOMMENDED STUDY MATERIALS\n\n- Innocence Lost/Target X (2005, 2006, also part of X-23: The Complete Collection)\n- New X-Men #20-32 (Vol 2, 2005, collected as New X-Men: Childhood's End)\n- X-Force (Vol 3, 2008)\n- All-New Wolverine (2015)"]

    $ Laura.database["wiki"] = [
        "Mutiefan Entry for X-23\n\nUtterly silent on the battlefield, this sultry assassin will steal your breath, your heart and your life. The woman known only as 'X-23' was born to be a lethal weapon, devoting her life to her training. Putting her ninja skills to good use, X never hesitates to strike, leaving nothing but broken bodies and heartache in her wake. Watch out for movement in the shadows, X-23 is on the prowl!"]

    $ Laura.database["comments"] = [
        f"{Laura.call_sign}: This is stupid. This is all stupid. Why do you insist on making me read these things? Is this punishment for some perceived failure in training?",
        f"{Rogue.call_sign}: cant tipe, laguhing"]

    return