init python:

    def all_Rogue_Clothes():
        Clothes = [
            Rogue_asymmetric_hair(),
            Rogue_black_bra(),
            Rogue_black_cage_bra(),
            Rogue_black_cage_thong(),
            Rogue_black_fishnet_top(),
            Rogue_black_garterbelt(),
            Rogue_black_gloves(),
            Rogue_black_jeans(),
            Rogue_black_keyhole_bra(),
            Rogue_black_lace_bra(),
            Rogue_black_lace_panties(),
            Rogue_black_shorts(),
            Rogue_black_stockings(),
            Rogue_black_tall_socks(),
            Rogue_black_tanktop(),
            Rogue_black_tape(),
            Rogue_black_tights(),
            Rogue_black_top(),
            Rogue_brown_jacket(),
            Rogue_classic_hair(),
            Rogue_green_athletic_shorts(),
            Rogue_green_bikini_bottoms(),
            Rogue_green_bikini_top(),
            Rogue_green_dress(),
            Rogue_green_headband(),
            Rogue_green_mesh_top(),
            Rogue_green_nighty(),
            Rogue_green_panties(),
            Rogue_greenyellow_boyshorts(),
            Rogue_greenyellow_sports_bra(),
            # Rogue_leather_jacket(),
            Rogue_leather_skirt(),
            Rogue_maroon_scarf(),
            Rogue_NIN_shirt(),
            Rogue_pink_swimsuit(),
            Rogue_plaid_coat(),
            Rogue_purple_eyeshadow(),
            Rogue_Rogue_belt(),
            Rogue_Rogue_suit(),
            Rogue_running_mascara(),
            Rogue_spiked_bracelets(),
            Rogue_spiked_collar(),
            Rogue_symmetric_hair(),
            Rogue_sweater_dress(),
            Rogue_thighhigh_boots(),
            Rogue_towel(),
            Rogue_wet_hair(),
            Rogue_yellow_boots(),
            Rogue_yellow_gloves()]

        return Clothes

    def Rogue_shopping_list():
        Clothes = [
            Rogue_black_cage_bra(),
            Rogue_black_cage_thong(),
            Rogue_black_garterbelt(),
            Rogue_black_keyhole_bra(),
            Rogue_black_lace_bra(),
            Rogue_black_lace_panties(),
            Rogue_black_stockings(),
            Rogue_black_tall_socks(),
            Rogue_black_tape(),
            Rogue_green_athletic_shorts(),
            Rogue_green_bikini_bottoms(),
            Rogue_green_bikini_top(),
            Rogue_green_dress(),
            Rogue_green_mesh_top(),
            Rogue_green_nighty(),
            Rogue_green_panties(),
            Rogue_greenyellow_boyshorts(),
            # Rogue_leather_jacket(),
            Rogue_leather_skirt()]

        return Clothes